//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlkemyLabs.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AlkemyLabEntities : DbContext
    {
        public AlkemyLabEntities()
            : base("name=AlkemyLabEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<inscription> inscription { get; set; }
        public virtual DbSet<subject_matter> subject_matter { get; set; }
        public virtual DbSet<teacher> teacher { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
